"""add_tenant_id

Revision ID: e510f1b014ac
Revises: 001
Create Date: 2026-05-30 01:16:22.512539

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e510f1b014ac'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('customers', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('deployments', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('incidents', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_index('ix_incidents_revenue_impact_desc', table_name='incidents')
    op.create_index(op.f('ix_incidents_estimated_revenue_impact_daily'), 'incidents', ['estimated_revenue_impact_daily'], unique=False)
    op.add_column('operational_events', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('payment_failures', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_index('ix_payment_failures_stripe_id', table_name='payment_failures')
    op.create_index(op.f('ix_payment_failures_stripe_payment_intent_id'), 'payment_failures', ['stripe_payment_intent_id'], unique=False)
    op.add_column('remediation_actions', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('revenue_events', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_constraint('revenue_events_incident_id_key', 'revenue_events', type_='unique')
    op.drop_index('ix_revenue_events_incident_id', table_name='revenue_events')
    op.create_index(op.f('ix_revenue_events_incident_id'), 'revenue_events', ['incident_id'], unique=True)
    op.add_column('support_tickets', sa.Column('tenant_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'tenant_id')
    op.drop_index(op.f('ix_revenue_events_incident_id'), table_name='revenue_events')
    op.create_index('ix_revenue_events_incident_id', 'revenue_events', ['incident_id'], unique=False)
    op.create_unique_constraint('revenue_events_incident_id_key', 'revenue_events', ['incident_id'])
    op.drop_column('revenue_events', 'tenant_id')
    op.drop_column('remediation_actions', 'tenant_id')
    op.drop_index(op.f('ix_payment_failures_stripe_payment_intent_id'), table_name='payment_failures')
    op.create_index('ix_payment_failures_stripe_id', 'payment_failures', ['stripe_payment_intent_id'], unique=False)
    op.drop_column('payment_failures', 'tenant_id')
    op.drop_column('operational_events', 'tenant_id')
    op.drop_index(op.f('ix_incidents_estimated_revenue_impact_daily'), table_name='incidents')
    op.create_index('ix_incidents_revenue_impact_desc', 'incidents', [sa.text('estimated_revenue_impact_daily DESC')], unique=False)
    op.drop_column('incidents', 'tenant_id')
    op.drop_column('deployments', 'tenant_id')
    op.drop_column('customers', 'tenant_id')
    op.drop_column('alerts', 'tenant_id')
    # ### end Alembic commands ###
